### ISSUE TITLE
提交前检查git log

### ISSUE THREAD

**Issue by xudafeng** [wqzhou0208/MacacaLibrary#2]
这里的log有问题 https://github.com/wqzhou0208/MacacaLibrary/commits/master

可以装 https://github.com/tj/git-extras 查看

**Comment by weiquzwq** [comment]
log的日志如下，安装git-extras之后使用过git-ignore来忽略文件，提交的用户的话现在也已经切换了，目前还看不出log哪里有问题，才疏学浅，有劳前辈指教
``zhouweiqudeMacBook-Pro:MacacaLibrary zhouweiqu$ git log
commit bb0d0ff968cf7d3e12737baa0a4a8f02171d902b
Author: 周伟衢 <zhouweiqu@zhouweiqudeMacBook-Pro.local>
Date:   Sun Jun 18 16:38:51 2017 +0800

    使用git-extras 设置ignore 文件

commit 4fff22fe1138ea6f09e950b2890d11d58a30dba9
Author: 周伟衢 <zhouweiqu@zhouweiqudeMacBook-Pro.local>
Date:   Sun Jun 18 16:14:54 2017 +0800

    忽略idea 和 DS_Store

commit c03cb172b0e03cf119bef972e10055ea44d20891
Author: 周伟衢 <zhouweiqu@zhouweiqudeMacBook-Pro.local>
Date:   Sun Jun 18 16:08:35 2017 +0800

    学习忽略文件

commit 2806d47ede24fa385dc6a45b9fa71d4a27a554ef
Author: 周伟衢 <zhouweiqu@zhouweiqudeMacBook-Pro.local>
Date:   Sun Jun 18 16:01:08 2017 +0800

    更新ignore``

**Comment by xudafeng** [comment]
👍
